-rオプション付lsコマンドの提出
iwamurahiroshi/ruby-practices pull request #9
Opened 2021-09-21 07:23 UTC by iwamurahiroshi

2021-09-21 09:05 UTC, komagata requested changes

2021-09-21 09:05 UTC, komagata commented on 05.ls/ls_3.rb
> +      print file&.ljust(longest_wordsize_per_column[i - 1] + 3)
putsとprintだと最後に改行がつくかどうかだけが違うので、その部分だけを分岐した方が共通のコードが多くなってメンテナンスしやすいコードになるかと思います〜

2021-09-21 14:57 UTC, iwamurahiroshi commented on 05.ls/ls_3.rb
> +      print file&.ljust(longest_wordsize_per_column[i - 1] + 3)
訂正してみました

2021-09-22 13:46 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-22 15:24 UTC, merged